Numpy

In [2]:
pip install numpy

     ---------------------------------------- 15.0/15.0 MB 4.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Ariel\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
pip install --upgrade pip

     ---------------------------------------- 2.1/2.1 MB 1.2 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9], ndmin = 3)
print(arr.ndim)
print(arr)

3
[[[1 2 3 4 5 6 7 8 9]]]


In [14]:
ceros = np.zeros((2,2))
ceros

array([[0., 0.],
       [0., 0.]])

In [15]:
unos = np.ones((2,2))
unos

array([[1., 1.],
       [1., 1.]])

In [16]:
aleatorios = np.random.rand(3,3)
aleatorios

array([[0.95088783, 0.67742854, 0.29582907],
       [0.75119939, 0.46291796, 0.01854912],
       [0.38221077, 0.71197273, 0.48474115]])

Operaciones

In [17]:
arr1 = [1,2,3]
arr2 = [1,2,3]

# Sumar
arr3 = np.add(arr1, arr2)
arr3

array([2, 4, 6])

In [19]:
# Restar
arr4 = np.subtract(arr1, arr2)
arr4

array([0, 0, 0])

In [20]:
# Multiplicar
arr5 = np.multiply(arr1, arr2)
arr5

array([1, 4, 9])

In [21]:
# Divide
arr6 = np.divide(arr1, arr2)
arr6

array([1., 1., 1.])

Agregacion

In [23]:
media = np.mean(arr1)
media

2.0

In [24]:
median = np.median(arr3)
median

4.0

In [25]:
maximo = np.max(arr5)
maximo

9

In [27]:
minimo = np.min(arr2)
minimo

1

Indexacion


In [33]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Slicing

In [43]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])